name: artifacts
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
       script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - name: publish js filename
        id: publish
        run: |
          find dist/assets -name "*.js" -type f -execdir echo "script-file={}" >> $GITHUB_OUTPUT \;
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: download-dist
      - name: output contents
        run : ls
      - name: outputfilename
        run: echo ${{needs.build.outputs.script-file}}